### ISSUE TITLE
作者大大帮忙看一下

### ISSUE THREAD

**Issue by jinzezhi** [Ernket/shepherd#1]
![image](https://user-images.githubusercontent.com/93123422/170441389-85e0102a-f65a-4a39-b286-a8b90a505a70.png)

**Comment by Ernket** [comment]
这是需要第三方库的，我忘记把需要的库写进去了不好意思
`pip3 install pyyaml`
你可以试着装一个yaml的库，这样就能解析了

**Comment by jinzezhi** [comment]
ok啦，谢谢师傅
