### ISSUE TITLE
fofa模块bug

### ISSUE THREAD

**Issue by PENG-PLUS** [Ernket/shepherd#2]
fofa.py:61 应该改成这样，去掉了导出fid的字段，这个字段需要企业会员
fofa_search_url = "https://fofa.info/api/v1/search/all?fields=ip,port,title,host,domain,country,province,city,country_name,header,server,protocol,banner,cert,isp,as_number,as_organization,latitude,longitude,icp,cname,type,jarm&page={}&email={}&key={}&qbase64={}&size=10".format(page_num,email,key,str_base64)

如果不改的话，返回结果为：{'error': True, 'errmsg': '[820001] 没有权限搜索fid字段'}

在这种情况下会报
[-]fofa模块存在问题：
local variable 'result' referenced before assignment

原因是异常处理没做好，在以下片段的代码里头，当errmsg存在于res.text时，result不会被创建，但紧接着又使用了result['results']，就会报变量在没定义前使用
```
    while True:
        fofa_search_url = "https://fofa.info/api/v1/search/all?fields=ip,port,title,host,domain,country,province,city,country_name,header,server,protocol,banner,cert,isp,as_number,as_organization,latitude,longitude,icp,cname,type,jarm&page={}&email={}&key={}&qbase64={}&size=10".format(page_num,email,key,str_base64)
        #print(fofa_search_url)
        res = requests.get(fofa_search_url, headers=header)
        if 'errmsg' not in res.text:
            result = json.loads(res.text)
        
        if len(result['results'])==0:           #如果当前页面返回的数据为0，说明已遍历完成，无需继续
```
可以改成
```
    while True:
        fofa_search_url = "https://fofa.info/api/v1/search/all?fields=ip,port,title,host,domain,country,province,city,country_name,header,server,protocol,banner,cert,isp,as_number,as_organization,latitude,longitude,icp,cname,type,jarm&page={}&email={}&key={}&qbase64={}&size=10".format(page_num,email,key,str_base64)
        #print(fofa_search_url)
        res = requests.get(fofa_search_url, headers=header)
        if 'errmsg' in res.text:
            print(res.text) #输出此时api返回结果
            continue #执行下次循环直到成功
        result = json.loads(res.text)
        
        if len(result['results'])==0:           #如果当前页面返回的数据为0，说明已遍历完成，无需继续
```

**Comment by Ernket** [comment]
收到，感谢建议
字段权限的变动这一块确实是比较麻烦的，其他模块的也存在api地址变动、非会员权限的变动导致模块无法使用的问题
刚刚仔细看了一下，这部分的逻辑确实处理的有问题，没写处理errmsg存在的情况，过段时间我本地测试后，会把这部分的应用到fofa.py中，其他模块存在的问题可能就无法去测试修复了，望大佬见谅
